FROM ubuntu:22.04

LABEL maintainer="NeoResearch"
ENV DEBIAN_FRONTEND noninteractive

# =====================================================================
# Nodejs packages & npm
RUN apt-get update \
    && apt-get install -y npm nodejs psmisc
# =====================================================================

RUN rm -rf /var/lib/apt/lists/*

WORKDIR /opt/

ADD package_basic_express.json /opt/package.json

RUN npm install
