FROM ubuntu:18.04

LABEL maintainer="NeoResearch"
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update \
    && apt-get install -y npm nodejs psmisc

# Docker packages
RUN apt-get update \
    && apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
RUN apt-key fingerprint 0EBFCD88
RUN add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
RUN apt-get update \
    && apt-get -y install docker-ce docker-ce-cli

RUN apt-get update \
    && apt-get -y install containerd.io

RUN rm -rf /var/lib/apt/lists/*

WORKDIR /opt/

ADD package.json /opt/

RUN npm install

# On docker run, start the consensus nodes
CMD ["/bin/bash", "/opt/run-CompilerExpress-RPC.sh"]
