FROM ubuntu:18.04
LABEL maintainer="NeoResearch"

RUN apt-get update \
    && apt-get install -y npm nodejs psmisc

ENV DEBIAN_FRONTEND noninteractive

WORKDIR /opt/

ADD package.json /opt/

RUN npm install

# On docker run, start the consensus nodes
CMD ["/bin/bash", "/opt/runHttpExpress.sh"]
